### ISSUE TITLE
Polyfill does not replace classList.toggle in IE11

### ISSUE THREAD

**Issue by schreifels** [yola/classlist-polyfill-old#14] opened 2016-08-31 23:37 UTC
## Unexpected behavior

In IE11, `classList.toggle` [does not take a second parameter](https://connect.microsoft.com/IE/feedback/details/878564/element-classlist-toggle-does-not-support-second-parameter), and the polyfill does not correct this. As an example, I created http://jsfiddle.net/4w949/64 , which contains the source code from yola/classlist-polyfill, along with a `console.log(document.body.classList.toggle);` below it.

In this case, `[ native code ]` is shown in the developer console in IE11.
## Expected behavior

For comparison, I took the [latest polyfill on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#JavaScript_shim_for_other_implementations) in the same fashion: http://jsfiddle.net/4w949/65 . Here, the `console.log` does not return `[ native code ]`; it (correctly) returns the implementation from the polyfill, which supports the second parameter.

**Comment by schreifels** [comment] 2016-08-31 23:53
Indeed, this is apparently a long-standing issue, see https://github.com/eligrey/classList.js/issues/44

Perhaps we could change the upstream of this module to be https://github.com/stevenvachon/classList.js , which contains a fix?

**Comment by snitch** [comment] 2016-09-05 01:07
@beck: This issue is now a priority.

**Comment by stevenvachon** [comment] 2016-09-07 16:10
I didn't know about this library. If you merge my fork with this one, I can remove mine -- I'd prefer not to keep it anyway.

**Comment by beck** [comment] 2016-09-12 19:24
This is a duplicate of: https://github.com/eligrey/classList.js/issues/54

I've started a new repo that is a proper github branch of the source.  I've opened a pull upstream:
https://github.com/eligrey/classList.js/pull/57

If merged, I'll merge down into our branch and cut a new release from https://github.com/yola/classlist-polyfill

**Closed as completed by beck** 2016-09-12 19:24 UTC
Labels: priority, frontend
